# This file was generated by GoReleaser. DO NOT EDIT.
class Civo < Formula
  desc "Cloud command-line tool"
  homepage "https://github.com/civo/cli"
  version "1.5.3"

  if OS.mac?
    url "https://github.com/civo/cli/releases/download/v#{version}/civo-#{version}-darwin-amd64.tar.gz"
    sha256 "9439efee615b476a2869a4f0ce0356c2d9c508245cf1a332e007685d1a1bee73"
  end

  def install
    bin.install "civo" => "civo"
    generate_completions_from_executable(bin/"civo", "completion")
    prefix.install_metafiles
  end

  test do
    system "#{bin}/civo", "version"
  end
end
