# This file was generated by GoReleaser. DO NOT EDIT.
class Civo < Formula
  desc "Civo cloud command-line tool"
  homepage "https://github.com/civo/cli"
  version "1.0.25"

  if OS.mac?
    url "https://github.com/civo/cli/releases/download/v1.0.25/civo-1.0.25-darwin-amd64.tar.gz"
    sha256 "3c99a9c10ccf4854466601af578db7761139ee100faaaef156d45fc7e4950a9c"
  end

  def install
    bin.install "civo" => "civo"
    output = Utils.popen_read("SHELL=bash #{bin}/civo completion bash")
    (bash_completion/"civo").write output
    output = Utils.popen_read("SHELL=zsh #{bin}/civo completion zsh")
    (zsh_completion/"civo").write output
    prefix.install_metafiles
  end

  test do
    system "#{bin}/civo", "version"
  end
end
