# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelmDocs < Formula
  desc "Automatically generate markdown documentation for helm charts"
  homepage "https://github.com/norwoodj/helm-docs"
  version "1.7.0"

  if OS.mac?
    url "https://github.com/norwoodj/helm-docs/releases/download/v1.7.0/helm-docs_1.7.0_Darwin_x86_64.tar.gz"
    sha256 "e34b4918ad92c6e553130029895aefc76a353f6ea7d968bbdf8037305dd22313"
  end

  def install
    bin.install "helm-docs"
  end

  test do
    system "#{bin}/helm-docs --version"
  end
end
