# This file was generated by GoReleaser. DO NOT EDIT.
class Hubble < Formula
  desc "Hubble observability tool for Cilium CNI"
  homepage "https://github.com/cilium/hubble"
  version "0.9.0"

  if OS.mac?
    url "https://github.com/cilium/hubble/releases/download/v0.9.0/hubble-darwin-amd64.tar.gz"
    sha256 "2cb4e437a80c40a4d03a33f71b7b5de4df122382e3ce05034d9113e4b5cad974"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cilium/hubble/releases/download/v0.9.0/hubble-darwin-arm64.tar.gz"
        sha256 "4d7bb949e5de5b5dacf9a56494bf795b97cc22374e9c01c355353fda6fb5c146"
      else
      end
    end
  end

  def install
    bin.install "hubble" => "hubble"
    output = Utils.popen_read("SHELL=bash #{bin}/hubble completion bash")
    (bash_completion/"hubble").write output
    output = Utils.popen_read("SHELL=zsh #{bin}/hubble completion zsh")
    (zsh_completion/"hubble").write output
    prefix.install_metafiles
  end

  test do
    system "#{bin}/hubble", "version"
  end
end
