# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K0sctl < Formula
  desc "k0s Management Tool"
  homepage "https://github.com/k0sproject/k0sctl"
  version "0.14.0"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/k0sproject/k0sctl/releases/download/v#{version}/k0sctl-darwin-x64"
    sha256 "1360436c4188790d413150663181392b6a76eafbd46ed59bf61498843753eaef"
  end

  def install
    bin.install "k0sctl-darwin-x64" => "k0sctl"
    output = Utils.popen_read("SHELL=bash #{bin}/k0sctl completion bash")
    (bash_completion/"k0sctl").write output
    output = Utils.popen_read("SHELL=zsh #{bin}/k0sctl completion zsh")
    (zsh_completion/"k0sctl").write output
    prefix.install_metafiles
  end
  test do
    system "#{bin}/k0sctl", "version"
  end
end
