# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K0sCtl < Formula
  desc "k0s Management Tool"
  homepage "https://github.com/linkerd/linkerd-smi"
  version "0.12.0-rc.3"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/k0sproject/k0sctl/releases/download/v0.12.0-rc.3/k0sctl-darwin-x64"
    sha256 "5bd901c07c78a6918db70fd68a46336bdf5111eebc176e23286ba4740639edeb"
  end

  def install
    bin.install "k0sctl-darwin-x64" => "k0sctl"
  end
end
