# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecolor < Formula
  desc "Colorize your kubectl output"
  homepage "https://github.com/dty1er/kubecolor"
  version "0.0.25"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/dty1er/kubecolor/releases/download/v#{version}/kubecolor_#{version}_Darwin_x86_64.tar.gz"
    sha256 "ecf6605f25aaa7bb8806690d7817eda0957e4e5359118ff7b3c7aef6e1f46848"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/dty1er/kubecolor/releases/download/v#{version}/kubecolor_#{version}_Darwin_arm64.tar.gz"
    sha256 "536385c9269f8c7f6a91044310710d1b2fad451a5b7640a67e67e4fffba17980"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dty1er/kubecolor/releases/download/v#{version}/kubecolor_#{version}_Linux_x86_64.tar.gz"
    sha256 "c126077e765ead50cfeca8e39886ddeee83c882cb54df726191f6762007a8015"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dty1er/kubecolor/releases/download/v#{version}/kubecolor_#{version}_Linux_arm64.tar.gz"
    sha256 "e6d2c379bf2ecd303a87e2be52d72fa37b02b0892e02c4a673615701e51e544b"
  end

  def install
    bin.install "kubecolor"
  end
end
