# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LinkerdSmi < Formula
  desc "Utility for Linkerd SMI"
  homepage "https://github.com/linkerd/linkerd-smi"
  version "0.2.7"

  if OS.mac?
    if Hardware::CPU.intel?
      url "https://github.com/linkerd/linkerd-smi/releases/download/v#{version}/linkerd-smi-#{version}-darwin"
      sha256 "41fad823a174e8f35d5af6b9c23b00a9f2473589eb12b46a56fbdfb56560ce95"
    elsif Hardware::CPU.arm?
      url "https://github.com/linkerd/linkerd-smi/releases/download/v#{version}/linkerd-smi-#{version}-darwin-arm64"
      sha256 "20767989fda983ae8b352cc95fca974ba1a2f2e8f9de51a3c91262c900a6993c"
    end
  end

  depends_on "linkerd"

  def install
    if OS.mac?
      if Hardware::CPU.intel?
        bin.install "linkerd-smi-#{version}-darwin" => "linkerd-smi"
      elsif Hardware::CPU.arm?
        bin.install "linkerd-smi-#{version}-darwin-arm64" => "linkerd-smi"
      end
    end
  end
end
