# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LinkerdSmi < Formula
  desc "Linkerd SMI Utility"
  homepage "https://github.com/linkerd/linkerd-smi"
  version "0.1.0"

  depends_on "linkerd"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/linkerd/linkerd-smi/releases/download/v0.1.0/linkerd-smi-0.1.0-darwin"
    sha256 "9e5b300d25b5cedd544f8ade5da765cf4038cef05a033ddb9bcdbd555b9ed3d4"
  end

  def install
    bin.install "linkerd-smi-0.1.0-darwin"
  end
end
