# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Talosctl < Formula
  desc "Talos Linux Utility"
  homepage "https://github.com/talos-systems/talos"
  version "v1.0.1"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/siderolabs/talos/releases/download/v1.0.1/talosctl-darwin-amd64"
    sha256 "10f6fbbc81e291c0e04c94b8f4f2577ac66b5058ba5fd1b14d316f50e34c83a0"
  end

  def install
    bin.install "talosctl-darwin-amd64" => "talosctl"
  end
end
