# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Talosctl < Formula
  desc "Talos Linux Utility"
  homepage "https://github.com/talos-systems/talos"
  version "v1.3.5"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/siderolabs/talos/releases/download/#{version}/talosctl-darwin-amd64"
    sha256 "a0c0dff1b5bf3348894ebb1fb2bea6d68ddb8f126eab40b4538742d34ffe2355"
  end

  def install
    bin.install "talosctl-darwin-amd64" => "talosctl"
  end
end
