# This file was generated by GoReleaser. DO NOT EDIT.
class TektoncdCli < Formula
  desc "Tekton CLI - The command line interface for interacting with Tekton"
  homepage "https://github.com/tektoncd/cli"
  version "0.23.1"

  if OS.mac?
    url "https://github.com/tektoncd/cli/releases/download/v0.23.1/tkn_0.23.1_Darwin_x86_64.tar.gz"
    sha256 "e66b80f385a73fc634b79a97ca7908666536974e2b855d9218ff53a78cc4a0ce"
  end

  def install
    bin.install_symlink "tkn" => "kubectl-tkn"
    bin.install "tkn" => "tkn"
    output = Utils.popen_read("SHELL=bash #{bin}/tkn completion bash")
    (bash_completion/"tkn").write output
    output = Utils.popen_read("SHELL=zsh #{bin}/tkn completion zsh")
    (zsh_completion/"_tkn").write output
    prefix.install_metafiles
  end

  test do
    system "#{bin}/tkn", "version"
  end
end
